### PR TITLE
Merge gzip support to upstream

### PR DESCRIPTION
**Pull request by fredoche**
Here is my attempt at merging both your forks. I tested it and it works for me. I'd be glad if it could be put 'upstream' .
Thx

### CODE REVIEW

**Comment by fredoche** [comment]
Hi, is there something I can do to help merge this feature?

**Comment by MathieuLoutre** [comment]
Hi @fredoche, sorry I've been slow replying to this PR. Firstly, I'm thankful you took the time to dig through the other fork to integrate them here.

As you may have seen, this has been suggested before. My stance at the time was (and still very much is) that gzip was out of the scope of this task, because there as tasks out there to gzip the files and this plugin, ideally should just be used to handle the transfer to/from AWS.

However, I do realise there's a difference in feature set between the old `grunt-s3` and this one, and since `grunt-s3` is no longer, people kind of expect this task to do gzip as well which is fair.

I'm curious why gzip-ing the files separately isn't very popular. Arguably, it's just adding the `grunt-contrib-compress` task to your grunt and setting the `contentType` for the file group. Am I missing something? Can you tell me why?

In the meantime, I'll have a look at the PR in details and see the impact it has on the code.

Thanks again!

**Comment by MathieuLoutre** [comment]
@fredoche I've added basic gzip support on `0.12.0`.
You first need to compress your files with `grunt-contrib-compress` using a compound extension (ex: `.css.gz`) and the plugin will set the correct content type  based on the first extension (ex: `.css`) and set the encoding to gzip. No need to set flags or exclude files.

If the naming convention (use elsewhere too) isn't working for you, you can still use the ContentType and ContentEncoding params to set the values.

**Comment by fredoche** [comment]
Ok interesting, should I also rename my links to .gz or does the plugin strips the additional extension when pushing to s3?
If it is the latter then I think it is indeed the right way to do it, combining grunt-compress and your plugin.
Thanks for your help

**Comment by MathieuLoutre** [comment]
Oh, I see what you're saying but here's how it works currently:

- Compress with `grunt-contrib-compress` and use `.css.gz` extension for the output: `build.css.gz`
- The plugin will upload `build.css.gz` (without changing the file name) with the content type of `build.css` and `gzip` for the encoding

In the HTML, you'd want to link to the .gz files directly as recommended by the AWS doc (they say to detect if the browser can support gzip and use one version or the other depending) like so:  
`<script src="https://s3-eu-west-1.amazonaws.com/yourbucket/styles/build.css.gz"></script>`

Now I could add a `gzipRename` option which would strip `.css` (or `.gz`) from the file name before the upload so you could get one or the other depending on the naming convention. How does that sound?

**Comment by fredoche** [comment]
It sound great to me with the gzipRename option.  I'll update my compress pipeline accordingly. Thanks !

**Comment by MathieuLoutre** [comment]
I'll work on that during the weekend. I'm happy that I found a way to integrate it without gzipping inside the task itself!

**Comment by MathieuLoutre** [comment]
@fredoche I've pushed it now actually if you want to have a go. Let me know what you think.

**Pull request closed without merging**
