### PR TITLE
Add support for MFA

### PR DESCRIPTION
**Pull request by martintreurnicht**
Adds support for MFA by wrapping `s3_options`, when using MFA it will prompt the user for their MFA code and create the temporary credentials required, these temporary credentials are valid for 12 hours by default, this could be made configurable in future updates

### CODE REVIEW

**Comment by MathieuLoutre** [comment]
That sounds great @martintreurnicht but the diff is unreadable for some reason. Any idea why? Did you reformat the code? (it needs a bit of tidying but I suspect your editor/workflow took that to the extreme haha!)
Also, why have you added `fs` as a package?

**Comment by martintreurnicht** [comment]
@MathieuLoutre Ok, i'll see if i can tidy it up. I think this has happened because of the way i had to wrap the entire workflow inside a function. I'll see what i can do to cleanup the diff.

`fs` is being used to write and read cached credentials to the local directory, if you have some suggestions around removing that dependency i'd be happy to make the change

**Comment by martintreurnicht** [comment]
@MathieuLoutre It seems this is because of all the whitespace changes, to see the true diff you can go to https://github.com/MathieuLoutre/grunt-aws-s3/pull/101/files?w=1#diff-cd021a6261e48fd008c205fb2717800f, i'm not sure how you use that option by default though

**Comment by MathieuLoutre** [comment]
Thanks @martintreurnicht, I had a look but I'm still a little confused. Is it really necessary to wrap the majority of the code in this callback when arguably most of the users haven't had the need for it so far? I'm very happy to add the feature, but I'd rather it not change the whole structure of the code if possible.

**Comment by martintreurnicht** [comment]
@MathieuLoutre I'll see what i can do to reduce the footprint of this change, unfortunately because of the nature of node's async nature this is the only way i saw that i can do it with minimal changes, but i'll see if i can reduce the changes even further

**Comment by joedelia** [comment]
Is anybody still working on this? We'd really love to have this in place as it would make our deployment process a lot easier!

**Comment by MathieuLoutre** [comment]
I'm still up to get that change done if it's useful but I don't have a lot of time (and know very little about MFA works at the moment). So if you're willing to do a PR with a small enough footprint (keep the code style, indentation etc.) then I'd love to take a look and merge it.

**Comment by martintreurnicht** [comment]
@MathieuLoutre I'm closing this PR, if anyone else would like to take the time to reformat this to conform to your specifications, they are welcome to do so

**Pull request closed without merging**
