### PR TITLE
Add more generlized support for different compression algorithms.

### PR DESCRIPTION
**Pull request by smeder**
This is primarily in support of using the task together with Brotli compression.

### CODE REVIEW

**Comment by MathieuLoutre** [comment]
This looks pretty good, thanks! (Sorry, I'm only seeing this now for some odd reason). I can't see any reason for not supporting other compression algorithms, just need to look over the code a bit more.

**Comment by MathieuLoutre** [comment]
This is published in 2.0.0

**Comment by MathieuLoutre** [comment]
Thanks again

**Comment by smeder** [comment]
Thanks for merging!

**Pull request merged**
